### ISSUE TITLE
Implement Time Series Component

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/repeat-site#20]
## Objective
Display time series data/metrics for one policy for the years 2020, 2025, 2030, 2040 and 2050

## Tasks
- [ ] (Insert tasks here)

## Acceptance Criteria
- [x] When a user selects the "Time Series" tab, user should see all available metrics for current policy being evaluated for the years 2020, 2025, 2030, 2040, and 2050 (no styling required) 
- [x] Note: Filter functionality need not be implemented for this ticket.
