### ISSUE TITLE
[Benchmark] Versus Toggle

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/repeat-site#27]
## Objective
Complete UI & Styling work for changing scenario (frozen policy vs. net zero scenario) to be compared to current policy being evaluated

## Tasks
- [ ] (Insert tasks here)

## Acceptance Criteria
- [x] Clicking vs. toggle will update chart view with proper UI components (emphasis box in proper place, selected state)
- [x] Clicking vs. toggle will update chart view to display raw value diffs for selected comparison scenario
