### ISSUE TITLE
[Benchmark] Absolute/Percentage Toggle

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/repeat-site#28]
## Objective
Implement raw value/percentage toggle button styling and functionality

## Tasks
- [ ] (Insert tasks here)

## Acceptance Criteria
- [x] When a user selects absolute value/percentage toggle, UI style is updated accordingly 
- [x] When a user selects toggle, diff values change accordingly (percentage vs raw value)
