### ISSUE TITLE
Implement CSV Export Functionality

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/repeat-site#30]
## Objective
For both the time series and benchmark views of the chart, user should be able to download raw data as a csv. Columns to be included in export are as follows: 

**Time Series**
- One column for each year represented (2020, 2025, 2030, 2040, 2050)

**Benchmark** (To be finalized by client) 
- 2019 raw values
- Frozen Policy 2020
- Frozen Policy 2050
- Current Policy Evaluated 2020
- Current Policy Evaluated 2050
- Net Zero Scenario 2020
- Net Zero Scenario 2050
- Current <> Frozen Delta (raw) 2020
- Current <> Frozen Delta (raw) 2050
- Current <> Frozen Delta (percentage) 2020
- Current <> Frozen Delta (percentage) 2050
- Current <> Net Zero Delta (raw) 2020
- Current <> Net Zero Delta (raw) 2050
- Current <> Net Zero Delta (percentage) 2020
- Current <> Net Zero Delta (percentage) 2050

## Tasks
- [ ] (Insert tasks here)

## Acceptance Criteria
- [ ] When user selects "Export as CSV" from benchmark view, CSV should be downloaded (Title TBD) and should contain all columns outlined above
- [ ] When user selects "Export as CSV" from time series view, CSV should be downloaded (Title TBD) and should contain all columns outlined above
