### ISSUE TITLE
Implement Factsheet Download 

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/repeat-site#31]
## Objective
In addition to exporting the table as a CSV, user should be able to download a PDF factsheet. 

## Tasks
- [ ] (Insert tasks here)

## Acceptance Criteria
- [ ] Factsheet download button is styled as shown in mockups
- [ ] When a user clicks the download factsheet button, PDF version of factsheet should be downloaded onto user's machine.
