### ISSUE TITLE
Table Styling

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/repeat-site#32]
## Objective
To style table and related components (filter and selection) in accordance with mockups

## Scope
- Scope selection (state vs. national)
- Filter By Buttons (Category and Subcategory)
- Category styling within table (color headers) 

## Tasks
- [ ] (Insert tasks here)

## Acceptance Criteria
- [x] Scope selection and filtering match style outlined in mockups
- [x] Table headers (pillars) are color coded for easier readability
