### ISSUE TITLE
Implement Table Pagination

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/repeat-site#34]
## Objective
Implement table pagination for both benchmark and time series views of table

## Design Clarification 
How many metrics to display on a single page? 

## Tasks
- [ ] (Insert tasks here)
- [ ] Page count and navigation 
- [ ] Add scroll functionality within table window

## Acceptance Criteria
- [ ] User can navigate to any page of results from pagination navigation 
- [ ] From any given page, user can navigate to the next, previous, first and last pages
- [ ] Ensure that functionality updates as metrics are filtered via the table search bar
