### ISSUE TITLE
Implement Filter Functionality

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/repeat-site#35]
## Objective
Implement filter functionality for both time series and benchmark views. 

## Scope
- [ ] Scope (national vs. state)
- [ ] Categories
- [ ] Subcategories populate based on category selected
- [ ] Subcategory filtering

## Tasks
- [ ] (Insert tasks here)

## Acceptance Criteria
- [ ] Filtering works as expected for **Time Series View**
- [ ] Filtering works as expected for **Benchmark View**

**Comment by james-minton** [comment]
@urimaxi basic filtering seems to be working but can only filter on one subcategory at a time. (I cannot add subcategories to the table as is possible with `nzap-site`.
