### ISSUE TITLE
Fullscreen Image Gallery (Design)

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/repeat-site#61]
## Objective
On the policy page, add functionality to view items in the "Details and Resources" carousel in fullscreen mode

From Jesse: 
> One note on the image gallery on the policy pages, can you make the images go full size if you click them? Right not it looks like just the thumbnails.

## Tasks
- [ ] Add designs for fullscreen mode into mockup (Jon) 
- [ ] Get quick client approval
- [ ] Once approved, update [this ticket](https://app.zenhub.com/workspaces/repeat-60aff19431215c000ed5746b/issues/hyperobjekt/repeat-site/62) with a link to finalized design
