### ISSUE TITLE
Update site to showcase two policies

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/repeat-site#65]
## Objective
At time of launch, the REPEAT team plans to release scorecards (and policy pages) for two tax packages: 
- the GREEN Act (from the House) 
- the Clean Energy for America Act (from the Senate) 

## Tasks
- [ ] Implement an index page to outline the two policies that users can dive further into (this should match the [mockups](https://www.figma.com/file/e3BrG5TGLUzOdr3I84bUmG/REPEAT?node-id=247%3A648)) 
- [ ] Add a policy page (with dummy data/placeholders) for each policy (each of these should also match the corresponding mockups) 

Note: URL paths tbd, placeholders for now

**Comment by ekmason** [comment]
## Internal QA Review
- [ ] Remove the "Evaluate the Policies" header (this is featured on other pages, but not the policies index page)
- [ ] Instead of bullet points for the plans, add a second scorecard (similar to the Biden plan scorecard)
- [ ] Update page header to match mockups

**Comment by ekmason** [comment]
@urimaxi Would you make sure that the titles of the policies featured on this page are as follows: 

- GREEN Act
- Clean Energy for America Act

**Comment by james-minton** [comment]
### Internal QA Review - Second Pass 

- [ ] "Read more" links should go to individual policy pages (they currently go back to the index page).* 
- [ ] Please add these new individual policies to nav menu


* Are the dummy pages constructed yet? See earlier request in this ticket, "Add a policy page (with dummy data/placeholders) for each policy (each of these should also match the corresponding mockups)".
